PortfolioDesign/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from portafolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

#añade informacion para que aparezcan las imagenes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, blog_extendido

app_name = 'blog'

urlpatterns = [
    path('', blog, name='blog'),
    path('<id_blog>',blog_extendido, name='blog_extendido'),
]

blog/models.py
import datetime
from django.db import models

# Create your models here.
class Blog(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='Blog/imagen/')
    fecha = models.DateField(datetime.date.today)
    
    def __str__(self) -> str:
        nombrePublicacion = 'Publicacion: ' + self.titulo
        return nombrePublicacion

portafolio/models.py
from django.db import models

# Create your models here.
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.
class Proyectos(models.Model):
    titulo = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    imagen = ImageField(upload_to='Portafolio/imagen/')
    enlace = URLField(blank=True)
    
    def __str__(self) -> str:
        nombreProyecto = "Titulo: " + self.titulo
        return nombreProyecto

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def blog(request):
    proyectos = Blog.objects.all()
    return render(request, 'blog.html',{'proyectos':proyectos})

def blog_extendido(request, id_blog):
    post = get_object_or_404(Blog, pk=id_blog)
    return render(request, 'blogExtendido.html',{'post':post})

portafolio/views.py
from django.shortcuts import render
from .models import Proyectos

# Create your views here.
def home(request):
    proyectos = Proyectos.objects.all()
    return render(request,'home.html',{'proyectos':proyectos})

blog/templates/blog.html
{% extends 'plantilla.html' %}

{% block contenido %}
            
<h1>Este es el blog</h1>

<div class="container">

    <div class="row gx-0 d-flex justify-content-center mb-5 ">
        {% for proyecto in proyectos %}
        <div class="container col-lg-4">

            <section class="mx-auto my-5" style="max-width: 23rem;">
                <div class="card">
                    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                        <img src="{{proyecto.imagen.url}}" class="img-fluid" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title font-weight-bold"><a>{{proyecto.titulo}}</a></h5>
                        <p class="mb-2">{{proyecto.fecha | date:'M d Y'}}</p>
                        <p class="card-text">{{proyecto.descripcion | truncatechars:100}}</p>
                        <hr class="my-4" />
                        <ul class="list-unstyled list-inline d-flex justify-content-between">
                            <li class="list-inline-item">
                                <a class="btn btn-primary" href="{% url 'blog:blog_extendido' proyecto.id %}">Visitar proyecto</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </section>
        </div>

        {% endfor %}
    </div>

</div>

{% endblock contenido %}

blog/templates/blogExtendido.html
{% extends 'plantilla.html' %}

{% block contenido %}
            
    <h1>Blog extendido</h1>

    <h2>{{post.titulo}}</h2>
    <p>{{post.descripcion}}</p>
    <img src="{{post.imagen.url}}" alt="{{post.titulo}}">
    <h3>{{post.fecha}}</h3>
    <a href="{% url 'blog:blog' %}">Ver todos los proyectos</a>

{% endblock contenido %}

portafolio/templates/home.html
{% extends 'plantilla.html' %}

{% block contenido %}
            
    <h1>Pagina de inicio</h1>
    {% for proyecto in proyectos %}
        <h2>{{proyecto.titulo}}</h2>
        <p>{{proyecto.descripcion}}</p>
        <img src="{{proyecto.imagen.url}}" alt="{{proyecto.titulo}}">
        <a href="{{proyecto.enlace}}">{{proyecto.enlace}}</a>
    {% endfor %}

{% endblock contenido %}

portafolio/templates/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!---Boostrap--->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <title>Portafolio Design</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" href="#">Logo</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block contenido %}
        
    {% endblock contenido %}
</body>
</html>